### ISSUE TITLE
Importing project by using the zip downloaded or cloned from github?

### ISSUE THREAD

**Issue by Virthuss** [justasm/DragLinearLayout#14]
Hi guys,

So I'm opening a new issue as asked in the last one.

Using android studio at the moment, trying to use your library without using compile 'com.jmedeisis:draglinearlayout:1.1.0' in the gradle file but by importing the zip file downloaded or cloned from github is not working.

When included, the project make gradle to send an error : Error:Cannot access first() element from an empty List. I can however open, build and run your project in a different android studio window, but importing it is still impossible. In my case this is preventing me to import  meesec's fork as well. I'm using the build tools version 23 and am targeting the devices using API 15 or above.

**Comment by justasm** [comment]
Thanks for bringing this to attention.

This seems to be caused by [an issue with a third party plugin](https://github.com/novoda/bintray-release/pull/66) used by DragLinearLayout for publishing to Bintray, which has since been updated to resolve the issue. I will update the project to reflect this.

Meanwhile, for a quick fix:
In `library/build.gradle`, replace `classpath 'com.novoda:bintray-release:0.2.10'` with `classpath 'com.novoda:bintray-release:0.3.4'`.

**Comment by Virthuss** [comment]
May I ask if I can apply this fix to  meesec's fork? As you know, I need his fork to be able to highlight some elements before dragging them.

**Comment by justasm** [comment]
I assume so - it's relatively quick and painless so give it a shot! You'll
have to speak with @meesec for support on features / issues specific to the
fork.

**Comment by Virthuss** [comment]
I'll give a try during the next week and give you my feedback as soon as possible. Thanks for your help :+1:
