### ISSUE TITLE
Implementing with Android's LayoutTransition 

### ISSUE THREAD

**Issue by Meeks91** [justasm/DragLinearLayout#15]
The implementation of the DragLinearLayout works fine until I also implement Android's LayoutTransition. 

I get this error:

``` 
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

And I get runtime errors on these two methods in the DragLinearLayout class : 
1. addView(draggedItem.view, switchPosition);  //called in on drag
2. onDrag(deltaY); // called in the onTouchEvent override method. 
```

I stopped it crashing by overriding onTouchEvent() in my implementing activity, and setting the setLayoutTransition parameter to null on the DraggerLinearLayout when the row is touched, then in the DragLinearLayout when onAnimaitonEnd is  called,  I call a method in my implementing activity and make the setLayoutTransition() parameter not null anymore. 

But this causes some lag, and on the row you're dragging when you stop the drag and let it settle, it disappears for a second and then reappears. 

Is there anyway to implement the LayoutTransition, or any other recommended techniques for using animations to add rows, and for animating the incrementally increasing size of the DragLinearLayout? 

Thanks in advance.

**Comment by justasm** [comment]
Thanks for bringing to attention. I will take a look at the issue later this week.

Meanwhile:
- Since merging #8, `DragLinearLayout` does essentially what you describe by clearing / setting the layout transition.
- The [notes sample][notes-sample] animates in rows using explicit [view property animation][view-prop-ani].

[notes-sample]: https://github.com/justasm/DragLinearLayout/blob/master/sample/src/main/java/com/jmedeisis/example/draglinearlayout/NoteActivity.java
[view-prop-ani]: http://developer.android.com/guide/topics/graphics/prop-animation.html#views

**Comment by Meeks91** [comment]
Thanks for the response, I look at the changed in #8, implemented them, and it worked well. 

Thanks !
