### ISSUE TITLE
Can't drag layout child

### ISSUE THREAD

**Issue by goldmont** [justasm/DragLinearLayout#28]
Hi, I'm trying to solve this problem but I don't understand why it occurs. My aim is to save buttons's positions in SharedPreferences in order to restore their position when the App is launched the next time. When SharedPreferences are empty, the drag and drop feature works fine. Instead, when I launch again the App, after the code loads the buttons's indexes, the drag and drop feature get stuck. I can't drag buttons. It's like the buttons are not set as draggable. Any solution? Thanks.

``` java

@SuppressLint("SetTextI18n, CommitPrefEdits")
public class MainActivity extends AppCompatActivity {

    SharedPreferences SP;
    SharedPreferences.Editor mEditor;
    DragLinearLayout dragLinearLayout;
    Button mButton, mButton2, mButton3, mButton4;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        SP = PreferenceManager.getDefaultSharedPreferences(getBaseContext());
        mEditor = SP.edit();

        dragLinearLayout = (DragLinearLayout) findViewById(R.id.container);

        mButton = (Button) findViewById(R.id.button);
        mButton2 = (Button) findViewById(R.id.button2);
        mButton3 = (Button) findViewById(R.id.button3);
        mButton4 = (Button) findViewById(R.id.button4);

        for(int mInt = 0; mInt < dragLinearLayout.getChildCount(); mInt++) {
            View mChild = dragLinearLayout.getChildAt(mInt);
            dragLinearLayout.setViewDraggable(mChild, mChild);
            dragLinearLayout.removeView(mChild);
            switch (mChild.getId()) {
                case R.id.button:
                    dragLinearLayout.addDragView(mButton, mButton, SP.getInt(Integer.toString(mButton.getId()), 0));
                    break;
                case R.id.button2:
                    dragLinearLayout.addDragView(mButton2, mButton2, SP.getInt(Integer.toString(mButton2.getId()), 1));
                    break;
                case R.id.button3:
                    dragLinearLayout.addDragView(mButton3, mButton3, SP.getInt(Integer.toString(mButton3.getId()), 2));
                    break;
                case R.id.button4:
                    dragLinearLayout.addDragView(mButton4, mButton4, SP.getInt(Integer.toString(mButton4.getId()), 3));
                    break;
            }
        }

        dragLinearLayout.setOnViewSwapListener(new DragLinearLayout.OnViewSwapListener() {
            @Override
            public void onSwap(View firstView, int firstPosition, View secondView, int secondPosition) {
                mEditor.putInt(Integer.toString(firstView.getId()), secondPosition).apply();
                mEditor.putInt(Integer.toString(secondView.getId()), firstPosition).apply();
            }
        });

    }
}

```

``` xml

<?xml version="1.0" encoding="utf-8"?>
<com.jmedeisis.draglinearlayout.DragLinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/container"
    android:paddingTop="20dp"
    android:gravity="center_horizontal">

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Button 1"
        android:id="@+id/button"
        android:layout_alignParentTop="true" />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Button 2"
        android:id="@+id/button2"
        android:layout_below="@+id/button"
        android:layout_centerHorizontal="true" />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Button 3"
        android:id="@+id/button3"
        android:layout_below="@+id/button2" />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Button 4"
        android:id="@+id/button4" />
</com.jmedeisis.draglinearlayout.DragLinearLayout>

```

**Comment by justasm** [comment]
I have not run your code, but there may be several issues at play:
1. `DragLinearLayout` requires you to use `removeDragView()` instead of `removeView()`. (It is a flaw in the library that it does not enforce this properly.) Easiest fix would be to use the former instead of the latter. Note that there is also no need to call `setViewDraggable()` as you do right before removing it, since `addDragView()` makes it draggable.
2. You are iterating over the Views in your ViewGroup as you are moving them around. An in-place sort is bound to cause issues if you don't carefully keep track of your loop counter, e.g. consider the case:
- Iteration 0
  `[A B C D]` -> remove View at position 0, i.e. A
  `[B C D]` -> move View A to saved position, e.g. 1
  `[B A C D]`
- Iteration 1
  `[B A C D]` -> remove View at position 1, i.e. A
  `[B C D]` -> move View A to saved position, 1 again
  `[B A C D]`
  ..
  i.e. B is never processed. It may be simpler to remove all the Views first and then add them in the right order.

Depending on your use-case, you may be better off creating and binding Views dynamically with an adapter, e.g. by using a [`RecyclerView`](http://developer.android.com/training/material/lists-cards.html#RecyclerView) instead of `DragLinearLayout`. [`ItemTouchHelper`](https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.html) can provide drag and drop support. You can [find a good overview and tutorial here](https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf).

**Comment by goldmont** [comment]
Hi,

I've solved using `RecyclerView`. Do you know how to add items to Array to a specific index which is saved into SharedPreferences? So I can restore the buttons order when the App is launched. Thanks again!
